import type { GithubFile, GithubRepoRef, IGitHubService } from "./types.js";

/**
 * Self-serve CI for target repositories (operational plan step 2, OP-02/OP-03).
 *
 * A repository without a GitHub Actions workflow can never pass the merge
 * gate — QA can only report `unverified`. CodeVia therefore:
 *   1. detects the repository's stack from its file list,
 *   2. renders `.github/workflows/codevia-ci.yml` (build + test, on pushes to
 *      `agent-task-*` branches and on every `pull_request` — drafts included),
 *   3. commits it on a dedicated `codevia-ci-setup` branch and opens a
 *      **Draft PR** for a human to review and merge (never a direct push to
 *      the base branch),
 *   4. after the PR is merged, records the workflow's real job names into
 *      `settings.metadata.requiredChecks` so the merge gate knows what green
 *      looks like (`requiredChecksPatch`, applied automatically the next time
 *      `repo-status` reads the repository).
 */

/** Stacks we can build a workflow for, in canonical template order. */
export type CiStack = "node" | "dotnet" | "python" | "go" | "maven";

export const CI_WORKFLOW_PATH = ".github/workflows/codevia-ci.yml";
export const CI_SETUP_BRANCH = "codevia-ci-setup";
/** Pushes that should run CI: the agent working branches (and setup branches). */
export const CI_PUSH_BRANCH_GLOB = "agent-task-*";

const STACK_ORDER: CiStack[] = ["node", "dotnet", "python", "go", "maven"];

/** Detect every stack present in a repository file list (canonical order). */
export function detectStacks(paths: string[]): CiStack[] {
  const has = (predicate: (p: string) => boolean): boolean => paths.some(predicate);
  const found = new Set<CiStack>();
  if (has((p) => p === "package.json" || p.endsWith("/package.json"))) found.add("node");
  if (has((p) => /\.csproj$/i.test(p) || /\.sln$/i.test(p))) found.add("dotnet");
  if (has((p) => p === "pyproject.toml" || p === "setup.py" || p === "requirements.txt")) found.add("python");
  if (has((p) => p === "go.mod")) found.add("go");
  if (has((p) => p === "pom.xml" || p.endsWith("/pom.xml"))) found.add("maven");
  return STACK_ORDER.filter((s) => found.has(s));
}

export interface CiTemplateOptions {
  /** Lockfile found for the node stack (affects `npm ci` vs `npm install`). */
  nodeLock?: "npm" | "yarn" | "pnpm";
  /** Whether dotnet/python/maven repos actually carry tests (skip step otherwise). */
  dotnetHasTests?: boolean;
  pythonHasTests?: boolean;
  mavenHasTests?: boolean;
}

/** Derive template options from the same file list (single source of truth). */
export function templateOptionsFromPaths(paths: string[]): CiTemplateOptions {
  const has = (predicate: (p: string) => boolean): boolean => paths.some(predicate);
  return {
    nodeLock: has((p) => p === "package-lock.json" || p === "npm-shrinkwrap.json")
      ? "npm"
      : has((p) => p === "pnpm-lock.yaml")
        ? "pnpm"
        : has((p) => p === "yarn.lock")
          ? "yarn"
          : undefined,
    dotnetHasTests: has((p) => /\.csproj$/i.test(p) && /test/i.test(p)),
    pythonHasTests:
      has((p) => /^tests?\//.test(p) || /(^|\/)test_[^/]+\.py$/.test(p) || /_test\.py$/.test(p)) ||
      has((p) => p === "pytest.ini" || p === "tox.ini"),
    mavenHasTests: has((p) => /^src\/test\//.test(p)),
  };
}

/** Stable check names: the job `name` in the template IS the recorded check name. */
export function ciJobName(stack: CiStack): string {
  return `codevia-${stack}`;
}

export function requiredChecksForStacks(stacks: CiStack[]): string[] {
  return stacks.map(ciJobName);
}

/** Render `.github/workflows/codevia-ci.yml` for the detected stacks. */
export function renderCiWorkflow(stacks: CiStack[], opts: CiTemplateOptions = {}): string {
  if (!stacks.length) throw new Error("Cannot render a CI workflow without a detected stack");
  const jobs: string[] = [];
  for (const stack of stacks) {
    jobs.push(renderJob(stack, opts));
  }
  return [
    "# CodeVia CI — generated by CodeVia for this repository.",
    "# Build + test on agent working branches and on every pull request,",
    "# INCLUDING draft PRs (the `pull_request` trigger below never skips drafts).",
    "# After this file merges, CodeVia records the job names below as the",
    "# project's requiredChecks so the merge gate knows what green means.",
    "name: CodeVia CI",
    "",
    "on:",
    "  push:",
    "    branches:",
    `      - "${CI_PUSH_BRANCH_GLOB}"`,
    "  pull_request:",
    "    types: [opened, synchronize, reopened, ready_for_review]",
    "  workflow_dispatch:",
    "",
    "concurrency:",
    "  group: codevia-ci-${{ github.ref }}",
    "  cancel-in-progress: true",
    "",
    "permissions:",
    "  contents: read",
    "",
    "jobs:",
    ...jobs,
    "",
  ].join("\n");
}

function renderJob(stack: CiStack, opts: CiTemplateOptions): string {
  const head = [`  ${stack}:`, `    name: ${ciJobName(stack)}`, "    runs-on: ubuntu-latest", "    steps:"];
  switch (stack) {
    case "node": {
      const install =
        opts.nodeLock === "yarn"
          ? { name: "Install dependencies", run: "yarn install --frozen-lockfile || yarn install" }
          : opts.nodeLock === "pnpm"
            ? {
                name: "Install dependencies",
                run: "corepack enable && pnpm install --frozen-lockfile || pnpm install",
              }
            : { name: "Install dependencies", run: "npm ci || npm install" };
      head.push(
        "      - uses: actions/checkout@v4",
        "      - name: Setup Node",
        "        uses: actions/setup-node@v4",
        "        with:",
        '          node-version: "22"',
        "      - name: Install dependencies",
        `        run: ${install.run}`,
        "      - name: Build",
        "        run: npm run build --if-present",
        "      - name: Test",
        "        run: npm test --if-present",
      );
      break;
    }
    case "dotnet": {
      head.push(
        "      - uses: actions/checkout@v4",
        "      - name: Setup .NET",
        "        uses: actions/setup-dotnet@v4",
        "        with:",
        '          dotnet-version: "8.0.x"',
        "      - name: Restore",
        "        run: dotnet restore",
        "      - name: Build",
        "        run: dotnet build --no-restore",
        "      - name: Test",
        opts.dotnetHasTests
          ? "        run: dotnet test --no-build --verbosity minimal"
          : '        run: echo "no test project detected — build only"',
      );
      break;
    }
    case "python": {
      head.push(
        "      - uses: actions/checkout@v4",
        "      - name: Setup Python",
        "        uses: actions/setup-python@v5",
        "        with:",
        '          python-version: "3.11"',
        "      - name: Install dependencies",
        "        run: |",
        "          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi",
        "          if [ -f pyproject.toml ]; then pip install -e . || true; fi",
        "          pip install pytest || true",
        "      - name: Test",
        opts.pythonHasTests ? "        run: python -m pytest -q" : "        run: python -m compileall -q .",
      );
      break;
    }
    case "go": {
      head.push(
        "      - uses: actions/checkout@v4",
        "      - name: Setup Go",
        "        uses: actions/setup-go@v5",
        "        with:",
        "          go-version-file: go.mod",
        "      - name: Build",
        "        run: go build ./...",
        "      - name: Test",
        "        run: go test ./...",
      );
      break;
    }
    case "maven": {
      head.push(
        "      - uses: actions/checkout@v4",
        "      - name: Setup Java",
        "        uses: actions/setup-java@v4",
        "        with:",
        "          distribution: temurin",
        '          java-version: "17"',
        "          cache: maven",
        "      - name: Build",
        "        run: mvn -B -q -DskipTests compile",
        "      - name: Test",
        opts.mavenHasTests ? "        run: mvn -B -q test" : "        run: mvn -B -q -DskipTests package",
      );
      break;
    }
  }
  return head.join("\n");
}

/**
 * The metadata patch that records the workflow's real job names as required
 * checks. Returns undefined when checks are already configured (explicit user
 * configuration always wins) or there is nothing to record.
 */
export function requiredChecksPatch(
  projectSettings: { metadata?: Record<string, unknown> } | undefined,
  repoName: string,
  stacks: CiStack[],
  multiRepo: boolean,
): Record<string, unknown> | undefined {
  const names = requiredChecksForStacks(stacks);
  if (!names.length) return undefined;
  const meta = projectSettings?.metadata;
  const byRepoRaw = meta?.requiredChecksByRepo;
  const byRepo: Record<string, unknown> =
    byRepoRaw && typeof byRepoRaw === "object" ? { ...(byRepoRaw as Record<string, unknown>) } : {};
  const current = Array.isArray(meta?.requiredChecks) ? (meta.requiredChecks as unknown[]) : undefined;
  const currentForRepo = byRepo[repoName] ?? current;
  if (Array.isArray(currentForRepo) && currentForRepo.length > 0) return undefined; // already configured
  if (multiRepo || Object.keys(byRepo).length > 0) {
    byRepo[repoName] = names;
    return { requiredChecksByRepo: byRepo };
  }
  return { requiredChecks: names };
}

/* ------------------------------------------------------------------ */
/* Proposal: branch + workflow commit + Draft PR (never a direct push) */
/* ------------------------------------------------------------------ */

export type CiSetupStatus = "created" | "pr-exists" | "already-has-ci" | "no-stack" | "branch-missing";

export interface CiSetupOutcome {
  repo: string;
  status: CiSetupStatus;
  stacks: CiStack[];
  branch?: string;
  prNumber?: number;
  prUrl?: string;
  workflowPath?: string;
  jobNames?: string[];
  detail?: string;
}

export async function proposeCiSetup(opts: {
  github: IGitHubService;
  repo: GithubRepoRef;
  repoName: string;
  baseBranch: string;
}): Promise<CiSetupOutcome> {
  const { github, repo, repoName, baseBranch } = opts;

  const entries = await github.listFiles(repo, baseBranch);
  const paths = entries.filter((e) => e.type === "blob").map((e) => e.path);
  const workflows = paths.filter((p) => p.startsWith(".github/workflows/") && /\.ya?ml$/.test(p));
  if (workflows.length) return { repo: repoName, status: "already-has-ci", stacks: [], detail: workflows.join(", ") };

  const stacks = detectStacks(paths);
  if (!stacks.length)
    return {
      repo: repoName,
      status: "no-stack",
      stacks,
      detail: "No package.json / *.csproj|*.sln / pyproject.toml / go.mod / pom.xml found on the base branch.",
    };

  const branches = await github.listBranches(repo);
  const source = branches.find((b) => b.name === baseBranch);
  if (!source)
    return { repo: repoName, status: "branch-missing", stacks, detail: `Base branch ${baseBranch} not found` };

  const yaml = renderCiWorkflow(stacks, templateOptionsFromPaths(paths));
  const jobNames = requiredChecksForStacks(stacks);

  // Reuse the setup branch when it already exists (retry-safe, never duplicated).
  const branchExists = branches.some((b) => b.name === CI_SETUP_BRANCH);
  const existingWorkflow = await github.getFile(repo, CI_WORKFLOW_PATH, CI_SETUP_BRANCH).catch(() => undefined);
  if (!branchExists) await github.createBranch(repo, CI_SETUP_BRANCH, source.sha);

  const open = (await github.listPullRequests(repo)).find((pr) => pr.state === "open" && pr.head === CI_SETUP_BRANCH);
  if (open) {
    return {
      repo: repoName,
      status: "pr-exists",
      stacks,
      branch: CI_SETUP_BRANCH,
      prNumber: open.number,
      prUrl: open.htmlUrl,
      workflowPath: CI_WORKFLOW_PATH,
      jobNames,
    };
  }

  if (!existingWorkflow) {
    const file: GithubFile = { path: CI_WORKFLOW_PATH, content: yaml };
    await github.commit(repo, CI_SETUP_BRANCH, "chore(ci): add CodeVia CI workflow", [file], source.sha);
  }

  const pr = await github.createPullRequest(
    repo,
    `chore(ci): add CodeVia CI workflow (${stacks.join(", ")})`,
    [
      `CodeVia generated a build/test workflow for this repository (detected stack: ${stacks.join(", ")}).`,
      "",
      `- Workflow: \`${CI_WORKFLOW_PATH}\``,
      `- Jobs / check names: ${jobNames.map((n) => `\`${n}\``).join(", ")}`,
      `- Triggers: pushes to \`${CI_PUSH_BRANCH_GLOB}\` and every \`pull_request\` (draft PRs included).`,
      "",
      "**Review and merge this Draft PR to activate CI.** Nothing was written to the base branch;",
      "once merged, CodeVia records the job names above as the project's required checks automatically.",
    ].join("\n"),
    CI_SETUP_BRANCH,
    baseBranch,
    { draft: true },
  );

  return {
    repo: repoName,
    status: "created",
    stacks,
    branch: CI_SETUP_BRANCH,
    prNumber: pr.number,
    prUrl: pr.htmlUrl,
    workflowPath: CI_WORKFLOW_PATH,
    jobNames,
  };
}
