import type {
  ChatRequest,
  ChatResponse,
  IModelProvider,
  ProviderModelInfo,
} from "./types.js";
import type { ID } from "../types.js";
import { logger } from "../logger.js";

/**
 * Mock AI provider — lets the entire platform be exercised end-to-end without any
 * real API key or network access. Useful for development, tests, and Simulation Mode.
 *
 * Used as default when no real provider key is configured (see ProviderRegistry).
 */
export class MockProvider implements IModelProvider {
  readonly id: ID;
  readonly type = "mock";
  readonly name = "Mock AI";

  private static MODELS: ProviderModelInfo[] = [
    {
      id: "mock-fast",
      displayName: "Mock Fast",
      contextWindow: 32_000,
      inputCostPer1k: 0,
      outputCostPer1k: 0,
      capabilities: {
        vision: false,
        tools: true,
        structuredOutput: false,
        code: true,
        reasoning: false,
        streaming: true,
      },
    },
    {
      id: "mock-strong",
      displayName: "Mock Strong",
      contextWindow: 128_000,
      inputCostPer1k: 0,
      outputCostPer1k: 0,
      capabilities: {
        vision: true,
        tools: true,
        structuredOutput: true,
        code: true,
        reasoning: true,
        streaming: true,
      },
    },
    {
      id: "mock-reasoning",
      displayName: "Mock Reasoning",
      contextWindow: 256_000,
      inputCostPer1k: 0,
      outputCostPer1k: 0,
      capabilities: {
        vision: false,
        tools: true,
        structuredOutput: true,
        code: true,
        reasoning: true,
        streaming: true,
      },
    },
  ];

  constructor(id: ID = "provider-mock") {
    this.id = id;
  }

  resolveApiKey(): string | undefined {
    return undefined;
  }

  async health(): Promise<boolean> {
    return true;
  }

  async listModels(): Promise<ProviderModelInfo[]> {
    return [...MockProvider.MODELS];
  }

  async chat(req: ChatRequest): Promise<ChatResponse> {
    const model = MockProvider.MODELS.find((m) => m.id === req.modelId) ?? MockProvider.MODELS[0];
    // Coin-flip a deterministic pseudo-cost/token count from the request.
    const lastUser = req.messages.filter((m) => m.role === "user").at(-1)?.content ?? "";
    const inputTokens = Math.max(8, Math.round(lastUser.length * 0.5));
    const outputTokens = Math.max(16, Math.round(inputTokens * 1.5));
    const content = this.composeReply(req);
    logger.debug(`mock chat [${model.id}]`, { inputTokens, outputTokens });
    return {
      content,
      json: this.tryJson(content),
      finishReason: "stop",
      usage: { inputTokens, outputTokens, totalTokens: inputTokens + outputTokens },
      modelId: model.id,
      providerId: this.id,
      costUsd: 0,
    };
  }

  private composeReply(req: ChatRequest): string {
    const lastUser = req.messages.filter((m) => m.role === "user").at(-1)?.content ?? "";
    const system = req.messages.find((m) => m.role === "system")?.content ?? "";
    const agentName = this.extractAgentName(system);
    return [
      `[Mock ${agentName ?? "Assistant"}]`,
      `Received: ${lastUser.slice(0, 200)}`,
      ``,
      `This is a simulated response generated by the Mock AI provider.`,
      `It keeps the platform fully testable without real API credentials.`,
      ``,
      `Planned action: analyze the request (step 1), inspect the repository (step 2), then produce a result.`,
      `If you see this in production, configure a real provider in Settings → Providers.`,
    ].join("\n");
  }

  private extractAgentName(system: string): string | undefined {
    const m = system.match(/You are ([^.\n]+)/i);
    return m?.[1]?.trim();
  }

  private tryJson(content: string): unknown | undefined {
    try {
      const trimmed = content.trim();
      if (trimmed.startsWith("{") || trimmed.startsWith("[")) return JSON.parse(trimmed);
    } catch {
      /* not JSON */
    }
    return undefined;
  }
}
