import type { Skill } from "../domain/entities.js";

/**
 * Built-in skill catalog. Skills are independent, attachable capabilities that
 * get injected into an agent's context. This is the "Skill Marketplace" backing
 * data — users can enable/disable, tag, and attach them to agents/projects.
 */
export const BUILTIN_SKILLS: Skill[] = [
  {
    id: "skill-dotnet",
    slug: "dotnet",
    name: ".NET Development",
    description: "Modern .NET (8/9) development: C#, ASP.NET Core, EF Core, minimal APIs.",
    category: "backend",
    instructions:
      "Use idiomatic C#, prefer async/await, DI via constructor injection, and structured logging. Follow the repository's .editorconfig and Directory.Build.props.",
    version: "1.0.0",
    tools: ["code", "test", "build", "repository"],
    dependencies: ["csharp", "aspnetcore"],
    compatibleAgentTypes: ["backend-developer", "system-architect", "database", "refactoring", "performance"],
    metadata: { language: "csharp" },
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-csharp",
    slug: "csharp",
    name: "C#",
    description: "C# language essentials, modern idioms, LINQ, records, patterns.",
    category: "backend",
    instructions: "Write modern C# with nullable reference types enabled.",
    version: "1.0.0",
    tools: ["code"],
    dependencies: [],
    compatibleAgentTypes: ["backend-developer", "refactoring", "performance", "qa-test"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-aspnetcore",
    slug: "aspnetcore",
    name: "ASP.NET Core",
    description: "ASP.NET Core Web APIs, middleware, routing, minimal APIs.",
    category: "backend",
    instructions: "Follow ASP.NET Core conventions; register services in Program.cs; use IOptions for config.",
    version: "1.0.0",
    tools: ["code", "test"],
    dependencies: ["csharp"],
    compatibleAgentTypes: ["backend-developer", "system-architect"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-blazor",
    slug: "blazor",
    name: "Blazor",
    description: "Blazor Server / WebAssembly UI development with MudBlazor.",
    category: "frontend",
    instructions: "Use component-based UI, @code blocks, injectable services; prefer MudBlazor for production-grade UI.",
    version: "1.0.0",
    tools: ["code", "ui"],
    dependencies: ["dotnet", "ui-design"],
    compatibleAgentTypes: ["frontend-developer", "uiux"],
    metadata: { uiFramework: "blazor" },
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-mudblazor",
    slug: "mudblazor",
    name: "MudBlazor",
    description: "MudBlazor .NET UI components, theming, responsive layouts and accessibility.",
    category: "frontend",
    instructions: "Use MudBlazor components and the MudThemeProvider; follow its responsive grid and accessibility patterns.",
    version: "1.0.0",
    tools: ["code", "ui"],
    dependencies: ["blazor", "dotnet", "ui-design"],
    compatibleAgentTypes: ["frontend-developer", "uiux", "backend-developer"],
    metadata: { uiFramework: "mudblazor" },
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-html",
    slug: "html",
    name: "HTML",
    description: "Semantic HTML5, accessibility, SEO-friendly document structure.",
    category: "frontend",
    instructions: "Prefer semantic elements, valid nesting, accessibility attributes, and progressive enhancement.",
    version: "1.0.0",
    tools: ["code", "ui"],
    dependencies: [],
    compatibleAgentTypes: ["frontend-developer", "uiux", "documentation"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-css",
    slug: "css",
    name: "CSS",
    description: "Modern CSS, layout, responsive design, design tokens and accessibility.",
    category: "frontend",
    instructions: "Use modern CSS (grid, flex, custom properties, logical properties); support RTL and dark/light themes.",
    version: "1.0.0",
    tools: ["code", "ui"],
    dependencies: [],
    compatibleAgentTypes: ["frontend-developer", "uiux"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-react",
    slug: "react",
    name: "React",
    description: "React 18+ development with hooks and modern patterns.",
    category: "frontend",
    instructions: "Use function components and hooks; keep components small; use a typed API client.",
    version: "1.0.0",
    tools: ["code", "ui"],
    dependencies: ["typescript"],
    compatibleAgentTypes: ["frontend-developer", "uiux"],
    metadata: { uiFramework: "react" },
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-nodejs",
    slug: "nodejs",
    name: "Node.js",
    description: "Node.js + TypeScript backend development and tooling.",
    category: "backend",
    instructions: "Use ESM where possible, structured logging, and typed domain models.",
    version: "1.0.0",
    tools: ["code", "test", "build"],
    dependencies: ["typescript"],
    compatibleAgentTypes: ["backend-developer", "devops", "refactoring"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-sqlserver",
    slug: "sqlserver",
    name: "SQL Server",
    description: "SQL Server schema design, T-SQL, indexing, and EF Core migrations.",
    category: "database",
    instructions: "Design normalized schemas; use indexes on hot query paths; guard migrations in approval-backed workflows.",
    version: "1.0.0",
    tools: ["code", "database"],
    dependencies: ["dotnet"],
    compatibleAgentTypes: ["database", "backend-developer", "security"],
    metadata: { database: "sqlserver" },
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-sqlite",
    slug: "sqlite",
    name: "SQLite",
    description: "SQLite design, local file databases, migrations and testing in .NET / Node projects.",
    category: "database",
    instructions: "Use SQLite for local/dev and embedded cases; keep migrations versioned and never store production secrets in the file.",
    version: "1.0.0",
    tools: ["code", "database"],
    dependencies: [],
    compatibleAgentTypes: ["database", "backend-developer"],
    metadata: { database: "sqlite" },
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-oracle",
    slug: "oracle",
    name: "Oracle Database",
    description: "Oracle SQL/PL/SQL, schema design and API integration patterns.",
    category: "database",
    instructions: "Follow Oracle SQL best practices (transaction handling, indexes, bind variables) and keep migrations reviewable.",
    version: "1.0.0",
    tools: ["code", "database"],
    dependencies: [],
    compatibleAgentTypes: ["database", "backend-developer", "performance"],
    metadata: { database: "oracle" },
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-postgresql",
    slug: "postgresql",
    name: "PostgreSQL",
    description: "PostgreSQL design, SQL, indexing, and migration workflows.",
    category: "database",
    instructions: "Use migrations (e.g. Prisma, EF Core, Flyway); never test migrations on production without approval.",
    version: "1.0.0",
    tools: ["code", "database"],
    dependencies: [],
    compatibleAgentTypes: ["database", "backend-developer", "security"],
    metadata: { database: "postgresql" },
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-docker",
    slug: "docker",
    name: "Docker",
    description: "Dockerfiles, multi-stage builds, compose, and container best practices.",
    category: "devops",
    instructions:
      "Use multi-stage builds, non-root users, minimal base images, and HEALTHCHECK where appropriate.",
    version: "1.0.0",
    tools: ["docker", "build"],
    dependencies: [],
    compatibleAgentTypes: ["devops", "release", "backend-developer"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-git",
    slug: "git",
    name: "Git",
    description: "Git workflow, branching, commits, conventional commits, and PR hygiene.",
    category: "devops",
    instructions:
      "Create feature branches, write conventional commits, open PRs, and never force-push shared branches.",
    version: "1.0.0",
    tools: ["git", "github"],
    dependencies: [],
    compatibleAgentTypes: ["devops", "release", "backend-developer", "code-reviewer"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-github",
    slug: "github",
    name: "GitHub",
    description: "GitHub repo, branch, commit, PR, issue, and webhook operations.",
    category: "devops",
    instructions:
      "Use GitHub as the source of truth. Keep secrets out of the repo; reference them via secretRef.",
    version: "1.0.0",
    tools: ["github", "git"],
    dependencies: ["git"],
    compatibleAgentTypes: ["devops", "release", "code-reviewer", "backend-developer"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-restapi",
    slug: "restapi",
    name: "REST API",
    description: "REST API design, versioning, OpenAPI/Swagger documentation.",
    category: "backend",
    instructions:
      "Design resource-oriented REST APIs, version them, document with OpenAPI, and validate inputs.",
    version: "1.0.0",
    tools: ["code", "http"],
    dependencies: [],
    compatibleAgentTypes: ["backend-developer", "system-architect", "qa-test"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-microservices",
    slug: "microservices",
    name: "Microservices",
    description: "Microservice boundaries, contracts, and distributed system patterns.",
    category: "architecture",
    instructions:
      "Define clear bounded contexts and contracts; prefer asynchronous communication for cross-service flows.",
    version: "1.0.0",
    tools: ["code", "http"],
    dependencies: [],
    compatibleAgentTypes: ["system-architect", "backend-developer"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-ui-design",
    slug: "ui-design",
    name: "UI Design",
    description: "Design systems, semantics, responsive layout, and accessibility.",
    category: "frontend",
    instructions:
      "Build accessible, responsive, and consistent UIs; respect the design system and dark/light theme tokens.",
    version: "1.0.0",
    tools: ["ui", "code"],
    dependencies: [],
    compatibleAgentTypes: ["uiux", "frontend-developer"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-ux",
    slug: "ux",
    name: "UX",
    description: "User experience flows, information architecture, and usability.",
    category: "frontend",
    instructions: "Evaluate user flows and information architecture; reduce friction and cognitive load.",
    version: "1.0.0",
    tools: ["ui"],
    dependencies: ["ui-design"],
    compatibleAgentTypes: ["uiux"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-security",
    slug: "security",
    name: "Security",
    description: "OWASP, input validation, secrets hygiene, and secure-by-default practices.",
    category: "security",
    instructions:
      "Always validate inputs, never log secrets, apply least privilege, and flag dangerous operations for approval.",
    version: "1.0.0",
    tools: ["code", "security"],
    dependencies: [],
    compatibleAgentTypes: ["security", "code-reviewer", "backend-developer", "qa-test"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-testing",
    slug: "testing",
    name: "Testing",
    description: "Unit, integration, API, and end-to-end testing strategy.",
    category: "qa",
    instructions:
      "Write fast, deterministic tests; cover critical paths; run the full suite on every pull request.",
    version: "1.0.0",
    tools: ["test", "code"],
    dependencies: [],
    compatibleAgentTypes: ["qa-test", "backend-developer", "frontend-developer"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-playwright",
    slug: "playwright",
    name: "Playwright",
    description: "Browser automation and end-to-end UI testing with Playwright.",
    category: "qa",
    instructions: "Write reliable e2e tests, use stable selectors, and isolate test state.",
    version: "1.0.0",
    tools: ["test", "ui"],
    dependencies: ["testing"],
    compatibleAgentTypes: ["qa-test", "frontend-developer"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-performance",
    slug: "performance",
    name: "Performance Optimization",
    description: "Profiling, bottlenecks, caching, and query optimization.",
    category: "performance",
    instructions: "Measure before optimizing; target measurable improvements; avoid premature optimization.",
    version: "1.0.0",
    tools: ["code", "test"],
    dependencies: [],
    compatibleAgentTypes: ["performance", "backend-developer", "database"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "skill-typescript",
    slug: "typescript",
    name: "TypeScript",
    description: "Typed JavaScript, strict mode, and typed APIs.",
    category: "backend",
    instructions: "Enable strict mode, avoid `any`, and define shared types for contract boundaries.",
    version: "1.0.0",
    tools: ["code"],
    dependencies: [],
    compatibleAgentTypes: ["backend-developer", "frontend-developer", "refactoring"],
    metadata: {},
    enabled: true,
    builtIn: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
