#!/usr/bin/env node
/**
 * Assemble the SPA from feature modules.
 *
 * The single `public/app.js` runtime file is generated by concatenating the
 * ordered fragments listed in `client/app/manifest.json`. The fragments are the
 * editable source of truth; `app.js` is the committed artifact that keeps the
 * no-build-step dev/test workflow (and the JSDOM regression tests that `eval`
 * it) working.
 *
 *   node scripts/build-app.mjs            # regenerate public/app.js
 *   node scripts/build-app.mjs --check    # fail if public/app.js is stale
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const MANIFEST_PATH = resolve(ROOT, "client/app/manifest.json");
const APP_DIR = resolve(ROOT, "client/app");
const OUTPUT_PATH = resolve(ROOT, "public/app.js");

export function readManifest() {
  return JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
}

/** Concatenate the ordered fragments into the single-file bundle. */
export function buildApp() {
  const manifest = readManifest();
  const parts = [];
  let expected = 0;
  for (const mod of manifest.modules) {
    const path = resolve(APP_DIR, mod.file);
    if (!existsSync(path)) throw new Error(`missing app fragment: ${mod.file}`);
    const content = readFileSync(path, "utf8");
    if (content.length === 0) throw new Error(`empty app fragment: ${mod.file}`);
    if (/\b(import|export)\s/.test(content)) {
      // Ignore the words inside string literals/comments; only flag a real
      // ES module statement at the start of a line.
      const hasModuleStatement = content
        .split("\n")
        .some((line) => /^\s*(import\s|export\s|export\s*\{|export\s*default)/.test(line));
      if (hasModuleStatement) {
        throw new Error(`${mod.file} must stay a plain concatenated script (no ES module syntax)`);
      }
    }
    parts.push(content);
    expected += mod.to - mod.from + 1;
    if (process.env.CODEVIA_VERBOSE) {
      console.log(
        `  ${mod.file.padEnd(36)} ${String(mod.from).padStart(4)}-${String(mod.to).padStart(4)}  ${mod.module}`,
      );
    }
  }
  const bundle = parts.join("");
  if (process.env.CODEVIA_VERBOSE) {
    const lines = bundle.split("\n").length - 1;
    console.log(`  → ${lines} lines (manifest expects ${expected})`);
  }
  return bundle;
}

export function isCurrentAppFresh() {
  return readFileSync(OUTPUT_PATH, "utf8") === buildApp();
}

const main = () => {
  const checkOnly = process.argv.includes("--check");
  const bundle = buildApp();
  const current = existsSync(OUTPUT_PATH) ? readFileSync(OUTPUT_PATH, "utf8") : "";
  if (checkOnly) {
    if (current !== bundle) {
      console.error("✗ public/app.js is stale — run `npm run build:app` to regenerate it.");
      process.exit(1);
    }
    console.log("✓ public/app.js is up to date with client/app/.");
    return;
  }
  writeFileSync(OUTPUT_PATH, bundle);
  console.log(`✓ assembled public/app.js (${bundle.split("\n").length - 1} lines) from client/app/.`);
};

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
