import type { Agent, AgentType, Project, Run, Task } from "../domain/entities.js";
import type { ProjectRepository, TaskRepository } from "../domain/repos.js";
import type { AgentRepository } from "./agent-repo.js";
import type { AgentRunner } from "./runner.js";
import type { AgentRouter } from "./router.js";
import type { IGitHubService } from "../github/types.js";
import type { ModelRepository, ProviderRepository } from "../ai/model-repo.js";
import type { ProviderRegistry } from "../ai/provider-registry.js";
import { defaultPlanFor, type PlanStep } from "./plan.js";
import { isAgentType } from "./generator.js";
import { realChatFor, extractJson, type RealChat } from "./llm.js";
import { live } from "../realtime/live.js";
import { logger } from "../logger.js";
import { projectBrief } from "../domain/project-brief.js";

/**
 * Autonomous task loop — the flow the project page promises:
 *
 *   task → research → breakdown → backend/frontend implement (code → git)
 *        → QA verifies → on failure back to implementers (bounded) → done
 *
 * Two intelligence levels:
 * - Real AI (a non-mock provider is active): task breakdown and file contents
 *   are generated by the model; research/QA findings feed the next phase.
 * - Deterministic (mock / no key): heuristic breakdown + task-specific change
 *   notes committed to git. The loop, the git commits, the PRs, the QA gate
 *   and the fix loop are all real — only the "thinking" is templated.
 *
 * The parent task status is owned by the caller (AgentManager.runTask): this
 * class throws on failure and returns a summary on success.
 */

export interface BreakdownItem {
  agentType: AgentType;
  title: string;
  description: string;
  files: string[];
}

/** Agent types allowed to own build/fix subtasks. */
export const IMPLEMENTERS: AgentType[] = ["backend-developer", "frontend-developer", "database", "uiux"];

export type PhaseExecutor = (task: Task, agent: Agent, project: Project, plan?: PlanStep[]) => Promise<Run>;

export interface AutonomousDeps {
  projectRepo: ProjectRepository;
  taskRepo: TaskRepository;
  agentRepo: AgentRepository;
  agentRunner: AgentRunner;
  agentRouter: AgentRouter;
  github: IGitHubService;
  modelRepo: ModelRepository;
  providerRepo: ProviderRepository;
  /** Omitted → the loop stays deterministic (no real-AI attempts). */
  providerRegistry?: ProviderRegistry;
  /** Test seam — defaults to running through the real AgentRunner. */
  executor?: PhaseExecutor;
  /** How many fix→re-verify cycles before giving up (default 2). */
  maxFixLoops?: number;
}

export interface AutonomousSummary {
  researchTaskId: string;
  buildTaskIds: string[];
  qaTaskIds: string[];
  fixLoops: number;
  usedRealAi: boolean;
  files: string[];
}

const slugify = (s: string): string =>
  s.toLowerCase().replace(/[^a-z0-9\u0600-\u06FF]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "task";

const cleanPath = (p: string): string | undefined => {
  const v = String(p ?? "").trim().replace(/^\/+/, "");
  if (!v || v.includes("..") || v.length > 200) return undefined;
  return v;
};

export function deterministicBreakdown(project: Project, task: Task): BreakdownItem[] {
  const text = `${task.title} ${task.description}`.toLowerCase();
  const uiLike = /ui|ux|page|screen|frontend|react|vue|angular|mobile|design|style|css|rtl|layout|رابط|صفحه|ظاهر|موبایل|راست/.test(text);
  const schemaLike = /migration|schema|database|sql|table|column|مایگریشن|دیتابیس|اسکیما|جدول/.test(text);
  const slug = slugify(task.title);
  const items: BreakdownItem[] = [
    {
      agentType: "backend-developer",
      title: `Implement (backend): ${task.title}`.slice(0, 120),
      description: task.description,
      files: [`docs/tasks/${task.id}-backend-${slug}.md`],
    },
  ];
  if (uiLike) {
    items.push({
      agentType: "frontend-developer",
      title: `Implement (frontend): ${task.title}`.slice(0, 120),
      description: task.description,
      files: [`docs/tasks/${task.id}-frontend-${slug}.md`],
    });
  }
  if (schemaLike) {
    items.push({
      agentType: "database",
      title: `Implement (database): ${task.title}`.slice(0, 120),
      description: task.description,
      files: [`docs/tasks/${task.id}-database-${slug}.md`],
    });
  }
  void project;
  return items;
}

/** Duty line prepended to every implementer subtask so each unit's job is explicit. */
export const IMPLEMENTER_DUTIES: Record<string, string> = {
  "backend-developer":
    "Your duty: implement the server-side work (APIs, services, business logic) for this subtask, commit the code, and open a PR.",
  "frontend-developer":
    "Your duty: implement the UI work (pages, components, client logic) for this subtask, commit the code, and open a PR.",
  database:
    "Your duty: implement the data work (schema, migrations, queries) for this subtask, commit it, and open a PR.",
  uiux:
    "Your duty: implement the UX/design work (layout, styles, user flows) for this subtask, commit it, and open a PR.",
};

export const QA_DUTY =
  "Your duty: verify the implementation listed below against the research brief. Report every failure precisely (what, where, expected vs actual) so the fix agent can act on it.";

/**
 * Deterministic research brief (no-AI fallback): requirements distilled from
 * the request, affected areas from keyword signals, owners from the
 * deterministic breakdown, repo signals, and standing risks. The project
 * definition selections are always embedded via the brief.
 */
export function deterministicBrief(project: Project, task: Task, repoFiles: string[], researchSummary: string): string {
  const text = `${task.title} ${task.description}`;
  const sentences = text
    .split(/[.\n؛]+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 3)
    .slice(0, 6);
  const lower = text.toLowerCase();
  const areas: string[] = [];
  if (/ui|ux|page|screen|design|style|رابط|صفحه|ظاهر/.test(lower)) areas.push("UI/pages");
  if (/api|endpoint|server|service|backend/.test(lower)) areas.push("backend APIs/services");
  if (/auth|login|permission|role/.test(lower)) areas.push("authentication/authorization");
  if (/migration|schema|table|database|sql|مایگریشن|دیتابیس/.test(lower)) areas.push("database schema");
  if (/test|qa|تست/.test(lower)) areas.push("test coverage");
  if (areas.length === 0) areas.push("general implementation");
  const owners = deterministicBreakdown(project, task).map((i) => i.agentType);
  return [
    `Research brief for "${task.title}" (deterministic — connect a real AI provider for model-written analysis).`,
    ``,
    `Requirements:`,
    ...sentences.map((s) => `- ${s}`),
    ``,
    `Affected areas: ${areas.join(", ")}.`,
    `Suggested owners: ${owners.join(", ")}.`,
    `Repository signals: ${repoFiles.length} file(s) visible on ${project.branch}; research run observed:`,
    ...researchSummary.split("\n").slice(0, 6).map((l) => `  ${l.slice(0, 140)}`),
    ``,
    projectBrief(project),
    ``,
    `Standing risks: secrets must stay out of git; merges/deploys/migrations need human approval; every change ships as a PR.`,
  ].join("\n");
}

export class AutonomousOrchestrator {
  constructor(private readonly deps: AutonomousDeps) {}

  private get maxFixLoops(): number {
    return this.deps.maxFixLoops ?? 2;
  }

  private execute: PhaseExecutor = (task, agent, project, plan) =>
    (this.deps.executor ?? ((t, a, p, pl) => this.deps.agentRunner.run({ task: t, agent: a, project: p, workspaceRoot: process.cwd(), plan: pl })))(
      task, agent, project, plan,
    );

  /** Run the full loop for a task. Throws on failure; returns a summary on success. */
  async run(taskId: string): Promise<AutonomousSummary> {
    const task = this.deps.taskRepo.findById(taskId)?.data;
    if (!task) throw new Error(`Task ${taskId} not found`);
    const project = this.deps.projectRepo.findById(task.projectId)?.data;
    if (!project) throw new Error(`Project ${task.projectId} not found`);

    // ---- Phase 0: preflight — every requirement checked before research ----
    await this.preflight(project);

    const chat = this.deps.providerRegistry
      ? realChatFor({ modelRepo: this.deps.modelRepo, providerRepo: this.deps.providerRepo, providerRegistry: this.deps.providerRegistry })
      : undefined;
    if (chat) logger.info("autonomous loop using real AI", { provider: chat.providerName, model: chat.modelLabel, taskId });
    else logger.info("autonomous loop running deterministic (no real AI provider)", { taskId });

    // ---- Phase 1: research -------------------------------------------------
    const researchAgent = this.needAgent(project.id, "research");
    const researchTask = this.spawn(task, `Research: ${task.title}`.slice(0, 120), task.description, "research");
    const researchRun = await this.execute(researchTask, researchAgent, project);
    this.mark(researchTask, researchRun.status === "succeeded" ? "succeeded" : "failed", runError(researchRun));
    if (researchRun.status !== "succeeded") throw new Error(`Research failed: ${runError(researchRun)}`);
    const researchSummary = summarizeRun(researchRun);

    // ---- Research brief: the research unit's analysis becomes the prompt ----
    // that every downstream unit works from (definition selections included).
    const brief = await this.researchBrief(chat, project, task, researchSummary);
    this.deps.taskRepo.upsert(
      { ...task, input: { ...(task.input ?? {}), researchBrief: brief.slice(0, 3000) }, updatedAt: new Date().toISOString() },
      { projectId: task.projectId, parentId: task.parentTaskId },
    );

    // ---- Phase 2: breakdown ------------------------------------------------
    const breakdown = await this.breakdown(chat, project, task, brief);
    if (breakdown.length === 0) throw new Error("Breakdown produced no implementer subtasks");

    // ---- Phase 3: implement (code → git → PR) -------------------------------
    const buildTaskIds: string[] = [];
    const files: string[] = [];
    for (const item of breakdown) {
      const agent = this.needAgent(project.id, item.agentType);
      const child = this.spawn(task, item.title, this.withDuty(item.agentType, item.description, brief), item.agentType);
      buildTaskIds.push(child.id);
      const plan = await this.implementPlan(chat, project, agent, child, item, brief);
      files.push(...item.files);
      const run = await this.execute(child, agent, project, plan);
      this.mark(child, run.status === "succeeded" ? "succeeded" : "failed", runError(run));
      if (run.status !== "succeeded") throw new Error(`${agent.name} failed: ${runError(run)}`);
    }

    // ---- Phase 4: QA gate + bounded fix loop --------------------------------
    const qaTaskIds: string[] = [];
    let fixLoops = 0;
    for (;;) {
      const qaChild = this.spawn(
        task,
        fixLoops === 0 ? `Verify: ${task.title}`.slice(0, 120) : `Re-verify (attempt ${fixLoops + 1}): ${task.title}`.slice(0, 120),
        `${QA_DUTY}\n\nImplementation of "${task.title}". Changed files:\n${files.map((f) => `- ${f}`).join("\n")}\n\nResearch brief:\n${brief.slice(0, 1500)}`,
        "qa-test",
      );
      qaTaskIds.push(qaChild.id);
      const qaAgent = this.needAgent(project.id, "qa-test");
      const qaRun = await this.execute(qaChild, qaAgent, project);
      this.mark(qaChild, qaRun.status === "succeeded" ? "succeeded" : "failed", runError(qaRun));
      if (qaRun.status === "succeeded") break;

      if (fixLoops >= this.maxFixLoops) {
        throw new Error(`QA still failing after ${fixLoops} fix loop(s): ${runError(qaRun)}`);
      }
      fixLoops += 1;
      // Route the failure back to an implementer (constrained to the loop's builders).
      const routed = this.deps.agentRouter.route(`fix ${qaRun.steps.map((s) => `${s.label} ${s.detail ?? ""}`).join(" ")}`.slice(0, 500));
      const fixType = breakdown.some((b) => b.agentType === routed) ? routed : breakdown[0].agentType;
      const fixAgent = this.needAgent(project.id, fixType);
      const fixItem = breakdown.find((b) => b.agentType === fixType) ?? breakdown[0];
      const qaErrors = runError(qaRun);
      const fixChild = this.spawn(
        task,
        `Fix (attempt ${fixLoops}): ${task.title}`.slice(0, 120),
        this.withDuty(fixType, `QA verification failed for "${task.title}". Fix exactly these failures:\n\n${qaErrors}\n\nOriginal request: ${task.description}`, brief),
        fixType,
      );
      buildTaskIds.push(fixChild.id);
      const fixPlan = await this.implementPlan(chat, project, fixAgent, fixChild, fixItem, brief, qaErrors);
      const fixRun = await this.execute(fixChild, fixAgent, project, fixPlan);
      this.mark(fixChild, fixRun.status === "succeeded" ? "succeeded" : "failed", runError(fixRun));
      if (fixRun.status !== "succeeded") throw new Error(`${fixAgent.name} fix failed: ${runError(fixRun)}`);
    }

    return { researchTaskId: researchTask.id, buildTaskIds, qaTaskIds, fixLoops, usedRealAi: Boolean(chat), files };
  }

  // ---- helpers ---------------------------------------------------------------

  private needAgent(projectId: string, type: AgentType): Agent {
    const agent = this.deps.agentRepo.byType(projectId, type);
    if (!agent || !agent.enabled) throw new Error(`No enabled agent of type ${type} in project ${projectId}`);
    return agent;
  }

  /**
   * Preflight: check every loop requirement up front so a task fails fast
   * with one clear checklist instead of dying mid-loop.
   */
  private async preflight(project: Project): Promise<void> {
    const problems: string[] = [];
    if (!project.configRepo || !project.configRepo.includes("/")) {
      problems.push("project has no repository (owner/name) — link one first");
    }
    for (const type of ["research", "qa-test"] as AgentType[]) {
      const a = this.deps.agentRepo.byType(project.id, type);
      if (!a) problems.push(`missing agent: ${type} (re-run onboarding)`);
      else if (!a.enabled) problems.push(`disabled agent: ${type} (enable it or re-run onboarding)`);
    }
    const builders = IMPLEMENTERS.filter((t) => {
      const a = this.deps.agentRepo.byType(project.id, t);
      return a && a.enabled;
    });
    if (builders.length === 0) {
      problems.push(`no enabled implementer (${IMPLEMENTERS.join("/")}) — re-run onboarding`);
    }
    try {
      const [owner, ...rest] = String(project.configRepo ?? "").split("/");
      if (owner && rest.length > 0) await this.deps.github.listBranches({ owner, name: rest.join("/") });
    } catch (err) {
      problems.push(`GitHub unreachable for ${project.configRepo}: ${String(err).slice(0, 140)}`);
    }
    if (problems.length > 0) {
      throw new Error(`Autonomous preflight failed:\n- ${problems.join("\n- ")}`);
    }
  }

  /** Prepend the unit's duty line and attach the research brief. */
  private withDuty(agentType: AgentType, body: string, brief: string): string {
    const duty = IMPLEMENTER_DUTIES[agentType] ?? `Your duty: complete this ${agentType} subtask and report the result.`;
    return `${duty}\n\nResearch brief:\n${brief.slice(0, 1800)}\n\nSubtask:\n${body}`.slice(0, 3000);
  }

  /**
   * The research unit's analysis, built into the prompt every downstream
   * unit works from. Real AI writes it when available; otherwise the
   * deterministic brief (task + selections + repo signals) is used.
   */
  private async researchBrief(chat: RealChat | undefined, project: Project, task: Task, researchSummary: string): Promise<string> {
    const files = await this.repoFiles(project).catch(() => [] as string[]);
    if (chat) {
      try {
        const raw = await chat.chat(
          "You are a senior business analyst writing implementation briefs. Reply with a concise structured brief, no fluff.",
          `Task: ${task.title}\n${task.description}\n\nProject definition (from the project setup selections):\n${projectBrief(project)}\n\nResearch run findings:\n${researchSummary}\n\nRepository files (sample):\n${files.slice(0, 40).join("\n") || "(unknown)"}\n\nWrite the implementation brief: 1) Requirements (bullets) 2) Affected areas/files 3) Suggested subtasks with owner agent type (backend-developer/frontend-developer/database/uiux) 4) Risks. Keep it under 400 words.`,
          1500,
        );
        if (raw.trim().length > 50) return raw.trim().slice(0, 3000);
      } catch (err) {
        logger.warn("AI research brief failed, using deterministic fallback", { taskId: task.id, err: String(err) });
      }
    }
    return deterministicBrief(project, task, files, researchSummary);
  }

  private spawn(parent: Task, title: string, description: string, agentType: AgentType): Task {
    const now = new Date().toISOString();
    const child: Task = {
      id: `task-${Math.random().toString(36).slice(2, 10)}`,
      projectId: parent.projectId,
      parentTaskId: parent.id,
      title,
      description,
      priority: parent.priority ?? "medium",
      status: "running",
      agentType,
      correlationId: parent.correlationId,
      input: { autonomous: true, parentTaskId: parent.id },
      createdAt: now,
      updatedAt: now,
    };
    this.deps.taskRepo.upsert(child, { projectId: child.projectId, parentId: parent.id });
    live.emit({ type: "task.updated", taskId: child.id, data: { status: "running", parentTaskId: parent.id } });
    return child;
  }

  private mark(child: Task, status: Task["status"], error?: string): void {
    this.deps.taskRepo.upsert(
      { ...child, status, error: status === "failed" ? error : undefined, updatedAt: new Date().toISOString() },
      { projectId: child.projectId, parentId: child.parentTaskId },
    );
    live.emit({ type: "task.updated", taskId: child.id, data: { status } });
  }

  private async breakdown(chat: RealChat | undefined, project: Project, task: Task, brief: string): Promise<BreakdownItem[]> {
    if (chat) {
      try {
        const files = await this.repoFiles(project).catch(() => [] as string[]);
        const raw = await chat.chat(
          "You are a senior engineering manager breaking work into implementer subtasks. Reply with ONLY a JSON array.",
          `Task: ${task.title}\n${task.description}\n\nResearch brief:\n${brief}\n\nProject definition (from the project setup selections):\n${projectBrief(project)}\nRepository files (sample):\n${files.slice(0, 40).join("\n") || "(unknown)"}\n\nBreak this into 1-4 implementer subtasks. Allowed agentType values: ${IMPLEMENTERS.join(", ")}. Each item: {"agentType","title","description","files":[1-5 repo-relative paths to create/modify]}. Reply with ONLY the JSON array, no prose.`,
          1500,
        );
        const parsed = extractJson(raw);
        const items = Array.isArray(parsed) ? parsed : [];
        const valid: BreakdownItem[] = [];
        for (const it of items.slice(0, 4)) {
          const rec = it as Record<string, unknown>;
          if (!isAgentType(rec.agentType) || !IMPLEMENTERS.includes(rec.agentType)) continue;
          const title = String(rec.title ?? "").trim();
          if (!title) continue;
          const files = (Array.isArray(rec.files) ? rec.files : []).map((f) => cleanPath(String(f))).filter(Boolean).slice(0, 5) as string[];
          valid.push({
            agentType: rec.agentType,
            title: title.slice(0, 120),
            description: String(rec.description ?? task.description),
            files: files.length ? files : [`docs/tasks/${task.id}-${rec.agentType}.md`],
          });
        }
        if (valid.length > 0) return valid;
        logger.warn("AI breakdown unusable, using deterministic fallback", { taskId: task.id });
      } catch (err) {
        logger.warn("AI breakdown failed, using deterministic fallback", { taskId: task.id, err: String(err) });
      }
    }
    return deterministicBreakdown(project, task);
  }

  /**
   * Implementer plan = the safe deterministic plan, with the write_file step
   * aimed at the breakdown's files and filled with generated content (real AI
   * code, or a task-specific change note in deterministic mode).
   */
  private async implementPlan(
    chat: RealChat | undefined,
    project: Project,
    agent: Agent,
    child: Task,
    item: BreakdownItem,
    brief: string,
    fixContext?: string,
  ): Promise<PlanStep[]> {
    const plan = defaultPlanFor(agent, child);
    const target = cleanPath(item.files[0]) ?? `docs/tasks/${child.id}.md`;
    const content = await this.fileContent(chat, project, agent, child, item, target, brief, fixContext);
    const writer = plan.find((s) => s.tool === "write_file");
    if (!writer) throw new Error(`${agent.name} has no permitted write step — cannot implement`);
    writer.input = { path: target, content, message: `[${agent.name}] ${child.title}`.slice(0, 120) };
    // Extra files from the breakdown ride along as follow-up write steps.
    const extra = item.files.map(cleanPath).filter(Boolean).slice(1, 3) as string[];
    if (extra.length > 0) {
      const idx = plan.indexOf(writer);
      const followUps: PlanStep[] = [];
      for (const path of extra) {
        followUps.push({
          label: `Write ${path}`,
          tool: "write_file",
          input: {
            path,
            content: await this.fileContent(chat, project, agent, child, { ...item, files: [path] }, path, brief, fixContext),
            message: `[${agent.name}] ${child.title}`.slice(0, 120),
          },
        });
      }
      plan.splice(idx + 1, 0, ...followUps);
    }
    return plan;
  }

  private async fileContent(
    chat: RealChat | undefined,
    project: Project,
    agent: Agent,
    child: Task,
    item: BreakdownItem,
    target: string,
    brief: string,
    fixContext?: string,
  ): Promise<string> {
    if (chat) {
      try {
        const files = await this.repoFiles(project).catch(() => [] as string[]);
        const raw = await chat.chat(
          `You are the ${agent.name} (${agent.role}). Output ONLY the file content, no fences, no explanations.`,
          `Repository files (sample):\n${files.slice(0, 40).join("\n") || "(unknown)"}\n\nSubtask: ${item.title}\n${item.description}\n\nResearch brief:\n${brief}\n${fixContext ? `\nQA failures to fix (address exactly these):\n${fixContext}\n` : ""}\nProject definition (from the project setup selections):\n${projectBrief(project)}\nWrite the complete content of "${target}" for project "${project.name}". Output ONLY the file content.`,
          4000,
        );
        const cleaned = raw.replace(/^```[a-z]*\n/i, "").replace(/\n```$/i, "").trim();
        if (cleaned.length > 20) return cleaned.slice(0, 24000);
      } catch (err) {
        logger.warn("AI codegen failed, using change-note fallback", { taskId: child.id, err: String(err) });
      }
    }
    return [
      `# ${child.title}`,
      ``,
      `> Implemented by ${agent.name} (deterministic mode — connect a real AI provider for generated code).`,
      ``,
      `## Request`,
      item.description || "(no description)",
      ``,
      `## Research brief`,
      brief.split("\n").slice(0, 24).join("\n"),
      ...(fixContext ? [``, `## QA feedback addressed`, fixContext.split("\n").slice(0, 12).join("\n")] : []),
      ``,
      `_Subtask ${child.id} · ${new Date().toISOString()}_`,
      ``,
    ].join("\n");
  }

  private async repoFiles(project: Project): Promise<string[]> {
    const [owner, ...rest] = String(project.configRepo ?? "").split("/");
    if (!owner || rest.length === 0) return [];
    const entries = await this.deps.github.listFiles({ owner, name: rest.join("/") }, project.branch);
    return entries.map((e) => e.path).filter((p) => !p.startsWith(".git/")).slice(0, 200);
  }
}



function summarizeRun(run: Run): string {
  return run.steps.map((s) => `- ${s.label}: ${s.status}${s.detail ? ` — ${s.detail}` : ""}`).join("\n");
}

function runError(run: Run): string {
  const failed = run.steps.filter((s) => s.status === "failed");
  if (failed.length === 0) return run.error ?? "unknown error";
  return failed.map((s) => `${s.label}: ${(s.detail ?? run.error ?? "").slice(0, 300)}`).join("\n");
}
