import { spawn } from "node:child_process";
import type { ToolContext, ToolDefinition, ToolResult } from "./types.js";

/** Coerce an input value to string. */
function str(v: unknown): string {
  return v == null ? "" : String(v);
}

/** Run a shell command in the workspace root, capturing output. */
function runCommand(cmd: string, cwd?: string): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const child = spawn(cmd, { cwd, shell: true, env: process.env });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (d) => (stdout += d.toString()));
    child.stderr.on("data", (d) => (stderr += d.toString()));
    child.on("close", (code) => resolve({ code: code ?? 1, stdout, stderr }));
    child.on("error", (err) => resolve({ code: 1, stdout: "", stderr: String(err) }));
  });
}

function toRepoRef(value: unknown): { owner: string; name: string } {
  const s = str(value);
  const [owner, ...rest] = s.split("/");
  return { owner, name: rest.join("/") };
}

export const listBranchesTool: ToolDefinition = {
  name: "list_branches",
  description: "List branches of the project repository.",
  dangerous: false,
  inputSchema: { type: "object", properties: { repo: { type: "string" } } },
  permissions: ["github.read"],
  timeoutMs: 15000,
  async execute(ctx: ToolContext, input) {
    const repo = toRepoRef(input.repo ?? ctx.project.configRepo);
    const branches = await ctx.github.listBranches(repo);
    return { ok: true, output: branches.map((b) => b.name).join("\n"), data: { branches } };
  },
};

export const listCommitsTool: ToolDefinition = {
  name: "list_commits",
  description: "List recent commits on a branch.",
  dangerous: false,
  inputSchema: { type: "object", properties: { repo: { type: "string" }, branch: { type: "string" } } },
  permissions: ["github.read"],
  timeoutMs: 15000,
  async execute(ctx: ToolContext, input) {
    const repo = toRepoRef(input.repo ?? ctx.project.configRepo);
    const branch = str(input.branch ?? ctx.project.branch);
    const commits = await ctx.github.listCommits(repo, branch);
    return {
      ok: true,
      output: commits.map((c) => `${c.sha.slice(0, 7)} ${c.message.split("\n")[0]}`).join("\n"),
      data: { commits },
    };
  },
};

export const readFileTool: ToolDefinition = {
  name: "read_file",
  description: "Read a file from the repository. Plan/understand only.",
  dangerous: false,
  inputSchema: { type: "object", properties: { path: { type: "string" } } },
  permissions: ["github.read"],
  timeoutMs: 15000,
  async execute(ctx: ToolContext, input) {
    const repo = toRepoRef(ctx.project.configRepo);
    const path = str(input.path);
    const file = await ctx.github.getFile(repo, path, ctx.project.branch);
    if (!file) return { ok: false, output: `File not found: ${path}` };
    return { ok: true, output: file.content.slice(0, 8000), data: { path, sha: file.sha } };
  },
};

export const writeFileTool: ToolDefinition = {
  name: "write_file",
  description: "Commit a file to the project repository on a branch.",
  dangerous: true,
  inputSchema: {
    type: "object",
    properties: { path: { type: "string" }, content: { type: "string" }, message: { type: "string" } },
  },
  permissions: ["github.write", "repository.write"],
  timeoutMs: 20000,
  async execute(ctx: ToolContext, input) {
    const repo = toRepoRef(ctx.project.configRepo);
    const branch = str(input.branch) || ctx.project.branch;
    const path = str(input.path) || `src/${ctx.agent.slug}.md`;
    const content = str(input.content) || `# ${ctx.agent.name} — ${new Date().toISOString()}\n\nGenerated change note.`;
    const message = str(input.message) || `[${ctx.agent.name}] update ${path}`;
    const commit = await ctx.github.commit(repo, branch, message, [{ path, content }]);
    ctx.logger.info("write_file committed", { path, sha: commit.sha, projectId: ctx.project.id });
    return { ok: true, output: `Committed ${commit.sha.slice(0, 7)} to ${branch}`, data: { sha: commit.sha } };
  },
};

export const createPullRequestTool: ToolDefinition = {
  name: "create_pull_request",
  description: "Create a pull request from a head branch to a base branch.",
  dangerous: true,
  inputSchema: {
    type: "object",
    properties: { title: { type: "string" }, body: { type: "string" }, head: { type: "string" }, base: { type: "string" } },
  },
  permissions: ["github.write"],
  timeoutMs: 20000,
  async execute(ctx: ToolContext, input) {
    const repo = toRepoRef(ctx.project.configRepo);
    const title = str(input.title) || `[${ctx.agent.name}] ${ctx.project.name}`;
    const body = str(input.body) || `Generated by the ${ctx.agent.name} agent.`;
    const head = str(input.head) || `agent-${ctx.agent.slug}`;
    const base = str(input.base) || ctx.project.branch;
    const pr = await ctx.github.createPullRequest(repo, title, body, head, base);
    ctx.logger.info("PR created", { number: pr.number, projectId: ctx.project.id });
    return { ok: true, output: `PR #${pr.number} created`, data: { number: pr.number, url: pr.htmlUrl } };
  },
};

export const runTestsTool: ToolDefinition = {
  name: "run_tests",
  description: "Run the project test command in the isolated workspace.",
  dangerous: false,
  inputSchema: { type: "object", properties: { command: { type: "string" }, cwd: { type: "string" } } },
  permissions: ["github.read"],
  timeoutMs: 120000,
  async execute(ctx: ToolContext, input) {
    const cmd = str(input.command ?? "npm test");
    const cwd = str(input.cwd ?? ctx.workspaceRoot);
    const res = await runCommand(cmd, cwd || undefined);
    return {
      ok: res.code === 0,
      output: `${res.stdout}\n${res.stderr}`.trim(),
      data: { code: res.code },
    };
  },
};

export const runBuildTool: ToolDefinition = {
  name: "run_build",
  description: "Run the project build command in the isolated workspace.",
  dangerous: false,
  inputSchema: { type: "object", properties: { command: { type: "string" }, cwd: { type: "string" } } },
  permissions: ["github.read"],
  timeoutMs: 120000,
  async execute(ctx: ToolContext, input) {
    const cmd = str(input.command ?? "npm run build");
    const cwd = str(input.cwd ?? ctx.workspaceRoot);
    const res = await runCommand(cmd, cwd || undefined);
    return { ok: res.code === 0, output: `${res.stdout}\n${res.stderr}`.trim(), data: { code: res.code } };
  },
};

export const searchTool: ToolDefinition = {
  name: "search",
  description: "Search project memory/knowledge by keyword.",
  dangerous: false,
  inputSchema: { type: "object", properties: { query: { type: "string" } } },
  permissions: ["memory.read"],
  timeoutMs: 15000,
  async execute(ctx: ToolContext, input) {
    void ctx;
    return { ok: true, output: `Search stub for "${str(input.query)}"` };
  },
};

export const requestApprovalTool: ToolDefinition = {
  name: "request_approval",
  description: "Request human approval before a dangerous action.",
  dangerous: true,
  inputSchema: { type: "object", properties: { action: { type: "string" }, detail: { type: "object" } } },
  permissions: ["github.write", "deployment.write"],
  timeoutMs: 60000,
  async execute(ctx: ToolContext, input) {
    if (!ctx.requestApproval) return { ok: false, output: "No approval channel configured" };
    const approved = await ctx.requestApproval(str(input.action), (input.detail as Record<string, unknown>) ?? {});
    return { ok: approved, output: approved ? "Approved" : "Rejected", requiresApproval: false, data: { approved } };
  },
};

export const CORE_TOOLS: ToolDefinition[] = [
  listBranchesTool,
  listCommitsTool,
  readFileTool,
  writeFileTool,
  createPullRequestTool,
  runTestsTool,
  runBuildTool,
  searchTool,
  requestApprovalTool,
];
